version: '3.1'

services:

  wordpress:
    build: wp-standard-user
    image: wp-dt
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./mytheme:/var/www/html/wp-content/themes/mytheme

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
